import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from config import (
    ALERT_EMAIL_FROM, ALERT_EMAIL_TO, ALERT_EMAIL_PASSWORD,
    RSI_OVERBOUGHT, RSI_OVERSOLD
)


def _send_email(subject: str, body: str):
    """Send an HTML email via Gmail SMTP."""
    if not all([ALERT_EMAIL_FROM, ALERT_EMAIL_TO, ALERT_EMAIL_PASSWORD]):
        print("  ⚠️  Email credentials not configured — skipping alert")
        return

    msg              = MIMEMultipart("alternative")
    msg["Subject"]   = subject
    msg["From"]      = ALERT_EMAIL_FROM
    msg["To"]        = ALERT_EMAIL_TO
    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(ALERT_EMAIL_FROM, ALERT_EMAIL_PASSWORD)
            server.send_message(msg)
        print(f"  📧 Alert sent: {subject}")
    except Exception as e:
        print(f"  ✗ Email failed: {e}")


def _alert_html(ticker: str, rsi: float, signal: str,
                price: float, condition: str, color: str) -> str:
    return f"""
    <div style="font-family:sans-serif;max-width:480px;padding:24px;
                border-left:4px solid {color};background:#f9f9f9;">
        <h2 style="color:{color};margin:0 0 8px">{condition} Alert: {ticker}</h2>
        <table style="width:100%;border-collapse:collapse">
            <tr><td style="padding:4px 8px;color:#555">Ticker</td>
                <td style="padding:4px 8px;font-weight:600">{ticker}</td></tr>
            <tr><td style="padding:4px 8px;color:#555">Current Price</td>
                <td style="padding:4px 8px;font-weight:600">${price:.2f}</td></tr>
            <tr><td style="padding:4px 8px;color:#555">RSI</td>
                <td style="padding:4px 8px;font-weight:600">{rsi:.2f}</td></tr>
            <tr><td style="padding:4px 8px;color:#555">ML Signal</td>
                <td style="padding:4px 8px;font-weight:600;color:{color}">{signal}</td></tr>
        </table>
        <p style="color:#888;font-size:12px;margin-top:16px">
            Generated by Quantitative Trading Signal Engine
        </p>
    </div>
    """


def check_and_alert(df_latest: dict):
    """
    df_latest: dict of {ticker: last_row_series}
    Sends email when RSI crosses overbought/oversold thresholds.
    """
    print("🔔 Checking alert thresholds...")
    triggered = 0

    for ticker, row in df_latest.items():
        rsi    = row.get("RSI",          float("nan"))
        price  = row.get("Close",         0.0)
        signal = row.get("Signal_Label",  "HOLD")

        if rsi > RSI_OVERBOUGHT:
            _send_email(
                subject=f"🔴 OVERBOUGHT Alert: {ticker} (RSI {rsi:.1f})",
                body=_alert_html(ticker, rsi, signal, price, "Overbought", "#e74c3c")
            )
            triggered += 1

        elif rsi < RSI_OVERSOLD:
            _send_email(
                subject=f"🟢 OVERSOLD Alert: {ticker} (RSI {rsi:.1f})",
                body=_alert_html(ticker, rsi, signal, price, "Oversold", "#27ae60")
            )
            triggered += 1

    if triggered == 0:
        print("  No thresholds crossed\n")
    else:
        print(f"  {triggered} alert(s) sent\n")
